### ISSUE TITLE
Plugin fails on startup

### ISSUE THREAD

**Issue by benomite** [bradfeehan/SublimePHPCoverage#28]
I am having difficulties making the plugin work.

On Sublime startup, with `debug` parameter to "true" the console give me this stack trace:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "SublimePHPCoverage in /home/benomite/.config/sublime-text-3/Installed Packages/PHP Code Coverage.sublime-package", line 56, in plugin_loaded
  File "/home/benomite/.config/sublime-text-3/Installed Packages/PHP Code Coverage.sublime-package/php_coverage/mediator.py", line 56, in add
    if not self.matcher.should_include(filename):
  File "/home/benomite/.config/sublime-text-3/Installed Packages/PHP Code Coverage.sublime-package/php_coverage/matcher.py", line 18, in should_include
    return self.included(filename) and not self.excluded(filename)
  File "/home/benomite/.config/sublime-text-3/Installed Packages/PHP Code Coverage.sublime-package/php_coverage/matcher.py", line 24, in included
    return self.match(config.include, filename)
  File "/home/benomite/.config/sublime-text-3/Installed Packages/PHP Code Coverage.sublime-package/php_coverage/matcher.py", line 37, in match
    if re.search(pattern, string):
  File "./python3.3/re.py", line 161, in search
TypeError: expected string or buffer
```

and 

``` 
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "SublimePHPCoverage in /home/benomite/.config/sublime-text-3/Installed Packages/PHP Code Coverage.sublime-package", line 105, in run
  File "/home/benomite/.config/sublime-text-3/Installed Packages/PHP Code Coverage.sublime-package/php_coverage/command.py", line 55, in should_include
  File "/home/benomite/.config/sublime-text-3/Installed Packages/PHP Code Coverage.sublime-package/php_coverage/matcher.py", line 18, in should_include
  File "/home/benomite/.config/sublime-text-3/Installed Packages/PHP Code Coverage.sublime-package/php_coverage/matcher.py", line 24, in included
  File "/home/benomite/.config/sublime-text-3/Installed Packages/PHP Code Coverage.sublime-package/php_coverage/matcher.py", line 37, in match
  File "./python3.3/re.py", line 161, in search
TypeError: expected string or buffer
```

I'm on Sublime text 3, Ubuntu 17.10

Do you have an idea what i am missing here?

Thanks a lot!

**Comment by benomite** [comment]
Plugin works as expected on Ubuntu 16.04
I wont be able to report more info about this error, feel free to close the issue if you want to.
Thanks!
